[package]
name = "ik_satisficer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_math = "0.11.3"
derive-new = "0.5.9"
derive_more = "0.99.17"
enum_dispatch = "0.3.12"
snafu = "0.7.5"
